# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_prangles <- function(U, V) {
    .Call('_RiemGrassmann_cpp_prangles', PACKAGE = 'RiemGrassmann', U, V)
}

cpp_pairdist <- function(U, V, dname) {
    .Call('_RiemGrassmann_cpp_pairdist', PACKAGE = 'RiemGrassmann', U, V, dname)
}

cpp_pdist <- function(INPUT1, dname) {
    .Call('_RiemGrassmann_cpp_pdist', PACKAGE = 'RiemGrassmann', INPUT1, dname)
}

cpp_pdist2 <- function(INPUT1, INPUT2, dname) {
    .Call('_RiemGrassmann_cpp_pdist2', PACKAGE = 'RiemGrassmann', INPUT1, INPUT2, dname)
}

